#!/usr/bin/env php
<?php

declare(strict_types=1);

$app = require_once __DIR__.'/bootstrap.php';

$argv ??= $_SERVER['argv'] ?? [];

array_shift($argv); // strip the application name

/** @var App\Application $app */
$app->handleConsoleCommand($argv);